apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: demo.bvrinfra.in   # <-- FIX THIS
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-app   # make sure this matches your service
            port:
              number: 80
